cluster:
  mkdir -p slurm_snake/`basename {workflow.main_snakefile}`/{rule} &&
  sbatch
    --partition={resources.partition}
    --cpus-per-task={resources.threads}
    --mem={resources.mem}
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=slurm_snake/`basename {workflow.main_snakefile}`/{rule}/{rule}-{wildcards}-%j.out
default-resources:
  - partition=amd
  - mem='8G'
  - time="0-00:60"
  - threads=1
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
# use-conda: True
